---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-networkpolicy-denier.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ (include "kube-networkpolicy-denier.selfSignedCABundleCertPEM" .) | b64enc | quote }}
  tls.crt: {{ (include "webhook.certPEM" .) | b64enc | quote }}
  tls.key: {{ (include "webhook.keyPEM" .) | b64enc | quote }}
