{{- $caCert := include "webhook.caBundleCertPEM" . -}}
{{- $crtPEM := include "webhook.certPEM" . -}}
{{- $keyPEM := include "webhook.keyPEM" . -}}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kube-networkpolicy-denier.fullname" . }}
  labels:
    {{- include "kube-networkpolicy-denier.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
webhooks:
  - clientConfig:
      caBundle: {{ ternary (b64enc $caCert) (b64enc (trim $crtPEM)) (empty $crtPEM) }}
      service:
        name: {{ include "kube-networkpolicy-denier.fullname" . }}
        namespace: {{ $.Release.Namespace | quote }}
        path: /validate
        port: {{ $.Values.service.port }}
    failurePolicy: Fail
    name: {{ include "kube-networkpolicy-denier.fullname" . }}.torbendury.de
    timeoutSeconds: 10
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - apiGroups:
          - networking.k8s.io
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - networkpolicies
