name: CI Pipeline

on:
  push:
    branches:
      - "feature/*"
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  # call e2etest and unittest workflows in local repo in parallel
  unittest:
    uses: ./.github/workflows/unittest.yml
    secrets: inherit
  e2etest:
    uses: ./.github/workflows/e2etest.yml
    secrets: inherit
