name: CI Pipeline

on:
  push:
    branches:
      - "feature/*"
  workflow_call:
    outputs:
      overall-result:
        description: "Overall test result"
        value: ${{ jobs.report.outputs.overall-result }}

jobs:
  unittest:
    uses: ./.github/workflows/unittest.yml
    secrets: inherit

  e2etest:
    uses: ./.github/workflows/e2etest.yml
    secrets: inherit

  report:
    needs: [unittest, e2etest]
    runs-on: ubuntu-latest
    outputs:
      overall-result: ${{ steps.check.outputs.result }}
    steps:
      - name: Check test results
        uses: ./.github/workflows/report.yml
        with:
          unittest-result: ${{ needs.unittest.outputs.test-result }}
          e2etest-result: ${{ needs.e2etest.outputs.test-result }}

      - name: Set overall result
        id: check
        run: |
          if [[ "${{ needs.unittest.outputs.test-result }}" == "success" && "${{ needs.e2etest.outputs.test-result }}" == "0" ]]; then
            echo "::set-output name=result::success"
          else
            echo "::set-output name=result::failure"
          fi
