name: CI Pipeline

on:
  workflow_call:

jobs:
  e2e_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.21.4"

      - name: Start Minikube
        uses: medyagh/setup-minikube@master
      - name: Cluster connectivity
        run: kubectl get pods -A
      - name: Build image, deploy Helm Chart and test in Minikube
        run: |
          export SHELL=/bin/bash
          make github
