name: E2E Test

on:
  workflow_call:
    outputs:
      test-result:
        description: "Test result"
        value: ${{ jobs.e2e_test.outputs.test-result }}

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    outputs:
      test-result: ${{ steps.test.outputs.result }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.21.5"

      - name: Start Minikube
        uses: medyagh/setup-minikube@master

      - name: Cluster connectivity
        run: kubectl get pods -A

      - name: Build image, deploy Helm Chart and test in Minikube
        id: test
        run: |
          export SHELL=/bin/bash
          make github
          TEST_RESULT=$?
          echo "::set-output name=result::$TEST_RESULT"
