# Whenever CI pushes a new Helm index, we want to merge `main` into `gh-pages` and push it.
# This will trigger a new GitHub Pages build, which will then be deployed to the `gh-pages` branch.
name: Pages Sync

on:
  push:
    branches:
      - gh-pages

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      # merge main into gh-pages and directly push it
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Merge main into gh-pages
        run: |
          git checkout gh-pages
          git merge main
          git push origin gh-pages
