name: CI Pipeline

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.21.4"

      - name: Go Test and Helm Lint
        run: make test
