name: Unit Tests

on:
  workflow_call:
    outputs:
      test-result:
        description: "Test result"
        value: ${{ jobs.unit_tests.outputs.test-result }}

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    outputs:
      test-result: ${{ steps.test.outputs.result }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.21.4"

      - name: Go Test and Helm Lint
        id: test
        run: |
          make test
          echo "::set-output name=result::success"
